### ISSUE TITLE
Change the license from AGPL to LGPL so that this code can be used in XWiki

### ISSUE THREAD

**Issue by mflorea** [xwiki-labs/hyperjson#3]
The current AGPL license is not compatible with XWiki's LGPL license which prevents us from integrating this library in XWiki for real-time editing. See https://jira.xwiki.org/browse/XWIKI-21575 .

**Comment by ghost** [comment]
See comment on another repository for the same issue: https://github.com/cryptpad/chainpad/issues/17#issuecomment-1898747992
